# standard jekyll configuration

permalink: date
pygments: true
markdown: rdiscount
baseurl: /

source: .
destination: ./_site
plugins: ./_plugins

# configuration required for some pages

domain: litao.me
title: Litao.Me
author: EaHydra
email: xxeaglenet@gmail.com

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

#github:
#   username: eahydra

disqus:
   id: eahydra
